### ISSUE TITLE
all PUCs web service

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum_ws#16]
As a consumer of Factotum data
I want to be able to understand what PUCs are available in Factotum
so that I can use data in my analysis

Definition of Done:
- endpoint of api.factotum.epa.gov/PUCs would return json response including
   -  dashboard_puc.id
   - dashboard_puc.gen_cat
    - dashboard_puc.prod_fam
    - dashboard_puc.prod_type
    - dashboard_puc.description
   - dashboard_puc.kind

**Comment by mcovalt** [comment]
This should be closed via #19. I'll let someone take a look to make sure first.

**Comment by mwfrost** [comment]
I agree that this is already functional at `http://127.0.0.1:8001/pucs/`. No pull request is needed.
