### ISSUE TITLE
Chem Wt Fraction web service

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum_ws#18]
As a Chemicals Dashboard developer
I want to retrieve product information by chemical
so that I can populate views of the Chemicals Dashboard

web service will populate this view of the Chemicals Dashboard: https://comptox.epa.gov/dashboard/dsstoxdb/results?search=DTXSID9022528#chemical-weight-fraction

Definition of Done
- given a DTXSID (dashboard_dsstoxlookup.sid), endpoint returns
   - product name = dashboard_product.title
   - dashboard_puc.gen_cat
   - dashboard_puc.prod_fam
   - dashboard_puc.prod_type
   - PUC = gen_cat:prod_fam:prod_type (three fields aggregated separated by colons)
   - min weight fraction = dashboard_ingredient.lower_wf_analysis
   - max weight fraction = dashboard_ingredient.upper_wf_analysis
**Note if lower_wf_analysis and upper_wf_analysis are blank, but dashboard_ingredient.central_wf_analysis is populated, then populate BOTH  min weight fraction and max weight fraction in the json with the central_wf_analysis
   - data type= dashboard_documenttype.title
   - source = dashboard_datasource.title

**Comment by mwfrost** [comment]
@kdionisio The default way to render a PUC as three strings in Factotum is to use dashes as delimiters between the three elements (like "PUC: Landscape/Yard - grill/camping fuel - "). You've requested colons above. Should we standardize on one approach or another?

**Comment by mcovalt** [comment]
Right now the payload for a product looks like this. When you filter by chemical, only that one chemical will be in the array.

This differs by the issue description in that more information is provided in the `puc`, `chemicals`, `data_type`, and `source` parts. Is this OK?

```json
{
  "id": 1867,
  "name": "Mama Bee Soothing Leg & Foot Creme",
  "puc": {
    "id": 145,
    "name": "Personal care: body hygiene",
    "gen_cat": "Personal care",
    "prod_fam": "body hygiene",
    "prod_type": "",
    "description": "",
    "kind": "FO"
  },
  "chemicals": [
    {
      "id": 151,
      "sid": "DTXSID6026296",
      "rid": "DTXRID00151",
      "name": "water",
      "cas": "7732-18-5",
      "qa": true,
      "min_weight_fraction": null,
      "max_weight_fraction": null,
      "data_type": {
        "name": "Unidentified",
        "description": null
      },
      "source": {
        "name": "Walmart MSDS",
        "url": "http://msds.walmartstores.com/",
        "description": ""
      }
    },
    {
      "id": 625,
      "sid": null,
      "rid": null,
      "name": "eau",
      "cas": "7732-18-5",
      "qa": false,
      "min_weight_fraction": null,
      "max_weight_fraction": null,
      "data_type": {
        "name": "Unidentified",
        "description": null
      },
      "source": {
        "name": "Walmart MSDS",
        "url": "http://msds.walmartstores.com/",
        "description": ""
      }
    },
    {
      "id": 362,
      "sid": null,
      "rid": null,
      "name": "Glycerin",
      "cas": "56-81-5",
      "qa": false,
      "min_weight_fraction": null,
      "max_weight_fraction": null,
      "data_type": {
        "name": "Unidentified",
        "description": null
      },
      "source": {
        "name": "Walmart MSDS",
        "url": "http://msds.walmartstores.com/",
        "description": ""
      }
    }
  ]
}
```

**Comment by kdionisio** [comment]
@mwfrost you can go ahead and use the dash as delimiter for the PUC so that it is consistent with what we have done in the past

**Comment by kdionisio** [comment]
QA note can be removed, all other fields can stay!
