### ISSUE TITLE
Combine Chemicals and TrueChemicals Web Service

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum_ws#37]
Combine the chemicals and truechemicals web service, the resulting web service called chemicals with the desired behavior:

`/chemicals/{rid}`  =>   sid, rid, name, cas, datadocument_id
`/chemicals/` => list of chemicals with sid, rid, name, cas, datadocument_id

Consolidate sid and rid into a single field called id

**Comment by mwfrost** [comment]
Endpoints under each current web service:

**Chemicals**
- chemicalsList `/chemicals/`
- chemicalsRidList `/chemicals/rid/`
- chemicalsRiddocList `/chemicals/riddoc/`
- chemicalsRead `/chemicals/{id}/`

**TrueChemicals**
- truechemicalsList `/truechemicals/`
- truechemicalsCasList `/truechemicals/cas/`
- truechemicalsNameList `/truechemicals/name/`
- truechemicalsSidList `/truechemicals/sid/`

**Comment by mwfrost** [comment]
Currently, the `/chemicals/{id}/` [endpoint](http://127.0.0.1:8001/#operation/chemicalsRead) returns a RawChem record, indexed by the `dashboard_rawchem.id` field. 

The new `/chemicals/{rid}/` endpoint will replace this, and will only return raw chemicals that have been assigned RIDs. The request will look like `/chemicals/rid/DTXRID003/`

**Comment by dmlyons2** [comment]
@mwfrost -> Your solution in the second paragraph looks great
