### ISSUE TITLE
Pagination of WS Results

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum_ws#8]
As a web consumer of our data
I would like to be able to get responses in chunks of 100
So that I do not have to wait so long if the result is 10000

The ws framework has a **meta** and **data** payloads - this ticket is to add a third payload called **paging** that will provide:

- a link to the current resource
- a link to the next resource
- a link to the previous resource (if available)
- total number of pages
- page you are on

**Comment by mwfrost** [comment]
@dmlyons2 If we are not using HTML for this, how should the previous/next links be implemented in the JSON? As modified versions of whatever request was submitted? So if a client requested `pucs?DTXSID9022528&level=3&page=2`, the service would return `"next": pucs?DTXSID9022528&level=3&page=3`?

**Comment by dmlyons2** [comment]
Hi @mwfrost - I would expect that the user would send an offset(page) in the request.
